### PR TITLE
Show own purchase prices within mode ticker

### PR DESCRIPTION
**Pull request by spitzlbergerj**
I have extended the ticker mode with the possibility to display my own purchase prices. Since the purchase prices don't change that often (at least for me as a not so active trader), I added them to the config.js as an array. When the purchase prices are displayed, they are colored red or green to make loss or gain visible.

### CODE REVIEW

**Comment by ezar** [comment]
may be interesting

**Comment by lavolp3** [comment]
looks good.
Can you add the change percentage against purchase price, ideally in the same line?
Would be helpful as well.
I see you mentioned profit/loss but I don't see anything in the code

**Comment by spitzlbergerj** [comment]
Hi,
i will have a look at it this weekend and extend the pull request accordingly

**Comment by spitzlbergerj** [comment]
Now the total performance compared to the own purchase price can be displayed

**Comment by spitzlbergerj** [comment]
.... and the conflicts in the .js are solved

**Comment by lavolp3** [comment]
Thanks.
Strongly considering extending this to the table and the grid.
If you want to do it, be my guest!

**Comment by lavolp3** [comment]
I see that your purchasePrice performance is shown in total (105%) and not relative to purchase price (+5%) 
I think relative is a better indicator and would like to change that. What do you think?

**Comment by spitzlbergerj** [comment]
Many thanks for the merge. I only use the ticker (without ticker :-), so only static display as lines. I am currently working on a few other modules for my project CaravanPi. If there is time afterwards, I will have a look at this.

And yes, change the relation gladly. I've been thinking about it for a few days now, which is better. In my portfolio, for example, 105% is shown, but 5% seems now better to me.

**Pull request merged**
